version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mlmodel-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ADMIN_PASS
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: mysqld --default-authentication-plugin=mysql_native_password

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: mlmodel-kafka1
    container_name: mlmodel-kafka1
    ports:
      - "39092:39092"
    environment:
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: IC8PnUQMSnO61JdfSV19Kw
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: BROKER://mlmodel-kafka1:19092,EXTERNAL://mlmodel-kafka1:39092,CONTROLLER://mlmodel-kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://mlmodel-kafka1:19092,EXTERNAL://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@mlmodel-kafka1:9093,2@mlmodel-kafka2:9093,3@mlmodel-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka1:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    hostname: mlmodel-kafka2
    container_name: mlmodel-kafka2
    ports:
      - "39093:39093"
    environment:
      CLUSTER_ID: IC8PnUQMSnO61JdfSV19Kw
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: BROKER://mlmodel-kafka2:19093,EXTERNAL://mlmodel-kafka2:39093,CONTROLLER://mlmodel-kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://mlmodel-kafka2:19093,EXTERNAL://localhost:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@mlmodel-kafka1:9093,2@mlmodel-kafka2:9093,3@mlmodel-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka2:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    hostname: mlmodel-kafka3
    container_name: mlmodel-kafka3
    ports:
      - "39094:39094"
    environment:
      CLUSTER_ID: IC8PnUQMSnO61JdfSV19Kw
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: BROKER://mlmodel-kafka3:19094,EXTERNAL://mlmodel-kafka3:39094,CONTROLLER://mlmodel-kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://mlmodel-kafka3:19094,EXTERNAL://localhost:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@mlmodel-kafka1:9093,2@mlmodel-kafka2:9093,3@mlmodel-kafka3:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./docker-compose/kafka/data/kafka3:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: mlmodel-kafdrop
    ports:
      - "9099:9000"
    environment:
      KAFKA_BROKERCONNECT: "mlmodel-kafka1:19092,mlmodel-kafka2:19093,mlmodel-kafka3:19094"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlmodel-django
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8088"
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - db
      - kafka1
      - kafka2
      - kafka3

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlmodel-consumer
    command: sh -c "python3 manage.py prompt_created_listener"
    restart: always
    depends_on:
      - db
      - kafka1
      - kafka2
      - kafka3
