# Generated by Django 4.1.13 on 2024-03-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('DONE', 'done')], default='PENDING', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mljobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
