# Generated by Django 4.1.13 on 2024-03-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_mljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='mljob',
            name='mlmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mljob', to='chatgpt.mlmodel'),
        ),
    ]
